version: '3.8'

services:
  fleet-manager:
    build: .
    container_name: process-engineering-fleet
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fleet-manager.rule=Host(`your-domain.com`)"
      - "traefik.http.routers.fleet-manager.entrypoints=websecure"
      - "traefik.http.routers.fleet-manager.tls.certresolver=myresolver"

  nginx:
    image: nginx:alpine
    container_name: fleet-manager-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - fleet-manager
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: fleet-manager-network
